version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /data1/source/node_modules
      - ./:/data1/source
    stdin_open: true